language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t rocky855/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rocky855/react-test npm test

after_success:
  - docker build -t rocky855/multi-client ./client
  - docker build -t rocky855/multi-nginx ./nginx
  - docker build -t rocky855/multi-server ./server
  - docker build -t rocky855/multi-worker ./worker
