language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t rocky855/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true rocky855/react-test npm test

after_success:
  - docker build -t rocky855/multi-client ./client
  - docker build -t rocky855/multi-nginx ./nginx
  - docker build -t rocky855/multi-server ./server
  - docker build -t rocky855/multi-worker ./worker

# login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

#push images to docker hub
  - docker push rocky855/multi-client
  - docker push rocky855/multi-nginx 
  - docker push rocky855/multi-server 
  - docker push rocky855/multi-worker 
  

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-950055239126'
  bucket_path: 'multi-docker'
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY  

  